export const ACADEMIC_ALIAS_GROUPS = Object.freeze([
  {
    category: "course_requirements",
    canonical: "prerequisites",
    aliases: [
      "prequisties",
      "prequisites",
      "prerequsities",
      "prerequisities",
      "preq",
      "preqs",
      "prereq",
      "prereqs",
      "pre requisite",
      "pre requisites",
      "pre-requisite",
      "pre-requisites",
      "course prerequisite",
      "course prerequisites",
    ],
  },
  {
    category: "course_requirements",
    canonical: "requirements",
    aliases: [
      "req",
      "reqs",
      "requirments",
      "requirment",
      "requiremnts",
      "requiremnt",
    ],
  },
  {
    category: "academic_subject",
    canonical: "blockchain",
    aliases: ["block chain", "block-chain", "blockchain"],
  },
  {
    category: "academic_subject",
    canonical: "natural language processing",
    aliases: ["nlp", "natural-language-processing", "naturallanguageprocessing"],
  },
  {
    category: "academic_subject",
    canonical: "machine learning",
    aliases: ["ml", "machinelearning", "machine-learning"],
  },
  {
    category: "academic_subject",
    canonical: "artificial intelligence",
    aliases: ["ai", "a.i.", "artificial-intelligence", "artificialintelligence"],
  },
  {
    category: "academic_subject",
    canonical: "mobile computing",
    aliases: ["mobilecomputing", "mobile-computing"],
  },
  {
    category: "academic_subject",
    canonical: "deep learning",
    aliases: ["deeplearning", "deep-learning", "dl"],
  },
  {
    category: "academic_subject",
    canonical: "computer vision",
    aliases: ["computervision", "computer-vision", "cv"],
  },
  {
    category: "academic_subject",
    canonical: "data science",
    aliases: ["datascience", "data-science"],
  },
  {
    category: "academic_subject",
    canonical: "cloud computing",
    aliases: ["cloudcomputing", "cloud-computing"],
  },
  {
    category: "academic_subject",
    canonical: "image processing",
    aliases: ["imageprocessing", "image-processing"],
  },
  {
    category: "academic_subject",
    canonical: "information retrieval",
    aliases: ["informationretrieval", "information-retrieval", "ir"],
  },
  {
    category: "academic_subject",
    canonical: "operating systems",
    aliases: ["operatingsystems", "operating-system", "os"],
  },
  {
    category: "academic_subject",
    canonical: "software engineering",
    aliases: ["softwareengineering", "software-engineering", "swe"],
  },
  {
    category: "academic_subject",
    canonical: "reinforcement learning",
    aliases: ["reinforcementlearning", "reinforcement-learning", "rl"],
  },
  {
    category: "faculty_role",
    canonical: "vice dean college of artificial intelligence",
    aliases: ["vice dean ai", "vice dean ai college", "vice dean artificial intelligence"],
  },
  {
    category: "faculty_role",
    canonical: "dean college of artificial intelligence",
    aliases: ["dean ai", "dean ai college", "dean artificial intelligence"],
  },
  {
    category: "faculty_role",
    canonical: "head of department",
    aliases: ["hod", "department head", "head department"],
  },
  {
    category: "faculty_role",
    canonical: "instructor",
    aliases: ["teacher", "lecturer", "prof", "professor", "doctor", "dr"],
  },
  {
    category: "policy_gpa",
    canonical: "GPA requirements",
    aliases: ["gpa req", "gpa reqs", "cgpa req", "cgpa reqs", "minimum gpa req"],
  },
  {
    category: "scholarship",
    canonical: "scholarship requirements",
    aliases: [
      "scholarship req",
      "scholarship reqs",
      "scholrship req",
      "financial aid req",
      "financial aid requirements",
    ],
  },
  {
    category: "transfer",
    canonical: "transfer requirements",
    aliases: [
      "transfer req",
      "transfer reqs",
      "credit transfer req",
      "credit transfer requirements",
      "course transfer",
      "equivalency",
    ],
  },
  {
    category: "attendance",
    canonical: "attendance requirements",
    aliases: [
      "attendance req",
      "attendance reqs",
      "attendence",
      "absence req",
      "absence reqs",
      "absence limit",
    ],
  },
  {
    category: "registration",
    canonical: "registration requirements",
    aliases: [
      "registration req",
      "registration reqs",
      "reg req",
      "reg reqs",
      "course reg",
      "course registration req",
      "semester reg",
      "enrolment",
      "enrollment req",
    ],
  },
  {
    category: "registration",
    canonical: "add drop",
    aliases: ["add/drop", "add-drop", "add and drop", "drop add"],
  },
]);

export const DOMAIN_VOCABULARY = Object.freeze([
  "academic",
  "absence",
  "attendance",
  "artificial",
  "intelligence",
  "blockchain",
  "career",
  "college",
  "computer",
  "computing",
  "course",
  "courses",
  "credit",
  "credits",
  "curriculum",
  "data",
  "dean",
  "department",
  "eligibility",
  "enrollment",
  "faculty",
  "financial",
  "gpa",
  "grade",
  "graduation",
  "instructor",
  "language",
  "learning",
  "machine",
  "mobile",
  "natural",
  "policy",
  "prerequisite",
  "prerequisites",
  "probation",
  "program",
  "registration",
  "requirements",
  "scholarship",
  "semester",
  "subject",
  "subjects",
  "transfer",
  "tuition",
  "vice",
  "vision",
]);

export const COURSE_FORMATTING_VOCABULARY = Object.freeze([
  "blockchain",
  "machine learning",
  "deep learning",
  "natural language processing",
  "mobile computing",
  "computer vision",
  "data science",
  "cloud computing",
  "image processing",
  "information retrieval",
  "operating systems",
  "software engineering",
  "reinforcement learning",
]);

export default {
  ACADEMIC_ALIAS_GROUPS,
  DOMAIN_VOCABULARY,
  COURSE_FORMATTING_VOCABULARY,
};
